[platformio]
default_envs = esp32-c3

[env]
platform = espressif32
monitor_speed = 115200

[env:esp32-c3]
framework = arduino
board = esp32-c3-devkitm-1
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    knolleary/PubSubClient@^2.8.0
    tzapu/WiFiManager@^2.0.17

[env:wokwi]
framework = arduino
board = esp32-c3-devkitm-1
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    knolleary/PubSubClient@^2.8.0
    tzapu/WiFiManager@^2.0.17
build_flags =
    -DWOKWI_SIMULATION

[env:native]
platform = native
lib_deps =
test_framework = unity
test_build_src = no
