[platformio]
default_envs = esp32-c3

[env]
platform = espressif32
framework = arduino
board = esp32-c3-devkitm-1
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    knolleary/PubSubClient@^2.8.0

[env:esp32-c3]

[env:wokwi]
build_flags =
    -DWOKWI_SIMULATION
