listener 8883 0.0.0.0
protocol mqtt
allow_anonymous false
require_certificate true
use_identity_as_username true
cafile /mosquitto/certs/ca/ca.crt
certfile /mosquitto/certs/broker/server.crt
keyfile /mosquitto/certs/broker/server.key
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
